name: Manually trigger prod and dev test

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Debug - Liste directory contents
      run: ls -R
    - name: run job
      run: az ml job create --file src/job_action_manual.yml --resource-group ml_test_1 --workspace-name mlops_azure_1 --stream
  
  prod-train:
    needs: train
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Debug - Liste directory contents
      run: ls -R
    - name: run job
      run: az ml job create --file src/job_prod.yml --resource-group production --workspace-name production --stream