name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      run: az ml job create --file src/job.yml --resource-group ml_test_1 --workspace-name mlops_azure_1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}


