name: 'Dependency review'

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge. now the step will be run after each PR in main"
      - name: Check out repo
        uses: actions/checkout@main
      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install pytest
        run: |
          python -m pip install -r requirements.txt
      - name: Run pytest
        run: | 
          pytest tests/

